---
services:
  vault-dev-1:
    image: hashicorp/vault:1.21.2
    container_name: vault
    ports:
      - "8200:8200/tcp"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    # command: "server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200"
    command: "sh /vault-init-simple.sh vcv"
    networks:
      - vcv-network
    volumes:
      - ./vault-dev-init.sh:/vault-dev-init.sh:ro
      - ./vault-init-simple.sh:/vault-init-simple.sh:ro

  vault-dev-2:
    image: hashicorp/vault:1.21.3
    container_name: vault-dev-2
    ports:
      - "8201:8200/tcp"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: "sh /vault-init-simple.sh vcv-2"
    networks:
      - vcv-network
    volumes:
      - ./vault-dev-init.sh:/vault-dev-init.sh:ro
      - ./vault-init-simple.sh:/vault-init-simple.sh:ro

  vault-dev-3:
    image: hashicorp/vault:1.21.4
    container_name: vault-dev-3
    ports:
      - "8202:8200/tcp"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: "sh /vault-init-simple.sh vcv-3"
    networks:
      - vcv-network
    volumes:
      - ./vault-dev-init.sh:/vault-dev-init.sh:ro
      - ./vault-init-simple.sh:/vault-init-simple.sh:ro

  openbao-dev-1:
    image: docker.io/openbao/openbao:2.5.1
    container_name: openbao-dev-1
    ports:
      - "1337:1337/tcp"
    environment:
      - OPENBAO_DEV_ROOT_TOKEN_ID=root
      - OPENBAO_DEV_LISTEN_ADDRESS=0.0.0.0:1337
    cap_add:
      - IPC_LOCK
    command: "sh /openbao-dev-init-1.sh"
    networks:
      - vcv-network
    volumes:
      - ./openbao-dev-init-1.sh:/openbao-dev-init-1.sh:ro

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: vcv
    ports:
      - "52000:52000/tcp"
    networks:
      - vcv-network
    depends_on:
      - vault-dev-1
      - vault-dev-2
      - vault-dev-3
      - openbao-dev-1
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./vcv.log:/var/log/app/vcv.log
      - ./settings.dev.json:/app/settings.dev.json
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 64M

networks:
  vcv-network:
    driver: bridge
